/********************************************************************************
** Form generated from reading UI file 'addlinkagerule.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ADDLINKAGERULE_H
#define UI_ADDLINKAGERULE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpacerItem>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_AddLinkageRule
{
public:
    QWidget *widget;
    QPushButton *btnSelAlarmSource;
    QTextEdit *textEdit_LinkagePara;
    QCheckBox *cbMap;
    QLabel *label_2;
    QLabel *label;
    QPushButton *btnOK;
    QLabel *label_5;
    QCheckBox *cbRecord;
    QCheckBox *cbPreview;
    QLabel *label_4;
    QLineEdit *lineEdit_ruleName;
    QPushButton *btnCancel;
    QTextEdit *textEdit_remark;
    QLabel *label_3;
    QCheckBox *cbTVWall;
    QLineEdit *lineEdit_alarmSource;
    QCheckBox *cbCapture;
    QCheckBox *cbPTZ;
    QLabel *label_6;
    QComboBox *cbAlarmType;
    QWidget *widget_3;
    QWidget *widget_2;
    QHBoxLayout *horizontalLayout;
    QSpacerItem *horizontalSpacer_3;
    QLabel *label_7;
    QSpacerItem *horizontalSpacer;
    QPushButton *btn_minimum;
    QPushButton *btn_close;
    QSpacerItem *horizontalSpacer_2;

    void setupUi(QDialog *AddLinkageRule)
    {
        if (AddLinkageRule->objectName().isEmpty())
            AddLinkageRule->setObjectName(QStringLiteral("AddLinkageRule"));
        AddLinkageRule->resize(625, 594);
        widget = new QWidget(AddLinkageRule);
        widget->setObjectName(QStringLiteral("widget"));
        widget->setGeometry(QRect(0, 30, 623, 564));
        btnSelAlarmSource = new QPushButton(widget);
        btnSelAlarmSource->setObjectName(QStringLiteral("btnSelAlarmSource"));
        btnSelAlarmSource->setGeometry(QRect(490, 95, 23, 23));
        btnSelAlarmSource->setMinimumSize(QSize(23, 23));
        btnSelAlarmSource->setMaximumSize(QSize(23, 23));
        QPalette palette;
        QBrush brush(QColor(210, 210, 210, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        QBrush brush1(QColor(120, 120, 120, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        btnSelAlarmSource->setPalette(palette);
        btnSelAlarmSource->setCursor(QCursor(Qt::OpenHandCursor));
        textEdit_LinkagePara = new QTextEdit(widget);
        textEdit_LinkagePara->setObjectName(QStringLiteral("textEdit_LinkagePara"));
        textEdit_LinkagePara->setGeometry(QRect(150, 205, 411, 191));
        textEdit_LinkagePara->setFrameShape(QFrame::NoFrame);
        cbMap = new QCheckBox(widget);
        cbMap->setObjectName(QStringLiteral("cbMap"));
        cbMap->setGeometry(QRect(400, 135, 61, 16));
        QPalette palette1;
        QBrush brush2(QColor(180, 180, 180, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        QBrush brush3(QColor(0, 0, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush3);
        QBrush brush4(QColor(255, 255, 255, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        QBrush brush5(QColor(255, 255, 220, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        cbMap->setPalette(palette1);
        cbMap->setChecked(false);
        label_2 = new QLabel(widget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(40, 50, 81, 16));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        label_2->setPalette(palette2);
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label = new QLabel(widget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(40, 10, 81, 16));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        label->setPalette(palette3);
        label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        btnOK = new QPushButton(widget);
        btnOK->setObjectName(QStringLiteral("btnOK"));
        btnOK->setGeometry(QRect(200, 520, 75, 23));
        btnOK->setMinimumSize(QSize(75, 23));
        btnOK->setMaximumSize(QSize(75, 23));
        btnOK->setCursor(QCursor(Qt::PointingHandCursor));
        btnOK->setFlat(true);
        label_5 = new QLabel(widget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(40, 195, 81, 21));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        label_5->setPalette(palette4);
        label_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        cbRecord = new QCheckBox(widget);
        cbRecord->setObjectName(QStringLiteral("cbRecord"));
        cbRecord->setGeometry(QRect(150, 165, 61, 16));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        cbRecord->setPalette(palette5);
        cbPreview = new QCheckBox(widget);
        cbPreview->setObjectName(QStringLiteral("cbPreview"));
        cbPreview->setGeometry(QRect(280, 165, 81, 16));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        cbPreview->setPalette(palette6);
        cbPreview->setChecked(false);
        label_4 = new QLabel(widget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(30, 135, 91, 16));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        label_4->setPalette(palette7);
        label_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_ruleName = new QLineEdit(widget);
        lineEdit_ruleName->setObjectName(QStringLiteral("lineEdit_ruleName"));
        lineEdit_ruleName->setGeometry(QRect(150, 10, 321, 20));
        lineEdit_ruleName->setFrame(false);
        btnCancel = new QPushButton(widget);
        btnCancel->setObjectName(QStringLiteral("btnCancel"));
        btnCancel->setGeometry(QRect(340, 520, 75, 23));
        btnCancel->setMinimumSize(QSize(75, 23));
        btnCancel->setMaximumSize(QSize(75, 23));
        btnCancel->setCursor(QCursor(Qt::PointingHandCursor));
        btnCancel->setFlat(true);
        textEdit_remark = new QTextEdit(widget);
        textEdit_remark->setObjectName(QStringLiteral("textEdit_remark"));
        textEdit_remark->setGeometry(QRect(150, 420, 411, 71));
        textEdit_remark->setFrameShape(QFrame::NoFrame);
        label_3 = new QLabel(widget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(40, 95, 81, 16));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        label_3->setPalette(palette8);
        label_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        cbTVWall = new QCheckBox(widget);
        cbTVWall->setObjectName(QStringLiteral("cbTVWall"));
        cbTVWall->setGeometry(QRect(400, 165, 71, 16));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        cbTVWall->setPalette(palette9);
        lineEdit_alarmSource = new QLineEdit(widget);
        lineEdit_alarmSource->setObjectName(QStringLiteral("lineEdit_alarmSource"));
        lineEdit_alarmSource->setGeometry(QRect(150, 95, 321, 20));
        lineEdit_alarmSource->setFrame(false);
        cbCapture = new QCheckBox(widget);
        cbCapture->setObjectName(QStringLiteral("cbCapture"));
        cbCapture->setGeometry(QRect(150, 135, 81, 16));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette10.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        cbCapture->setPalette(palette10);
        cbPTZ = new QCheckBox(widget);
        cbPTZ->setObjectName(QStringLiteral("cbPTZ"));
        cbPTZ->setGeometry(QRect(280, 135, 61, 16));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        cbPTZ->setPalette(palette11);
        label_6 = new QLabel(widget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(40, 415, 81, 21));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette12.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette12.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette12.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette12.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        label_6->setPalette(palette12);
        label_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        cbAlarmType = new QComboBox(widget);
        cbAlarmType->setObjectName(QStringLiteral("cbAlarmType"));
        cbAlarmType->setGeometry(QRect(150, 50, 321, 22));
        cbAlarmType->setFrame(false);
        widget_3 = new QWidget(AddLinkageRule);
        widget_3->setObjectName(QStringLiteral("widget_3"));
        widget_3->setGeometry(QRect(320, 870, 623, 3));
        widget_3->setMinimumSize(QSize(0, 3));
        widget_3->setMaximumSize(QSize(16777215, 3));
        widget_2 = new QWidget(AddLinkageRule);
        widget_2->setObjectName(QStringLiteral("widget_2"));
        widget_2->setGeometry(QRect(0, 0, 623, 33));
        widget_2->setMinimumSize(QSize(0, 33));
        widget_2->setMaximumSize(QSize(16777215, 33));
        horizontalLayout = new QHBoxLayout(widget_2);
        horizontalLayout->setSpacing(0);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        horizontalSpacer_3 = new QSpacerItem(10, 20, QSizePolicy::Minimum, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_3);

        label_7 = new QLabel(widget_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush4);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Light, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Mid, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush4);
        palette13.setBrush(QPalette::Active, QPalette::BrightText, brush4);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush4);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush3);
        palette13.setBrush(QPalette::Active, QPalette::Shadow, brush3);
        palette13.setBrush(QPalette::Active, QPalette::AlternateBase, brush3);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipBase, brush5);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipText, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush4);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::Light, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette13.setBrush(QPalette::Inactive, QPalette::BrightText, brush4);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::Shadow, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush5);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::Light, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::BrightText, brush4);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::Shadow, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush5);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush3);
        label_7->setPalette(palette13);
        QFont font;
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        label_7->setFont(font);

        horizontalLayout->addWidget(label_7);

        horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer);

        btn_minimum = new QPushButton(widget_2);
        btn_minimum->setObjectName(QStringLiteral("btn_minimum"));
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(btn_minimum->sizePolicy().hasHeightForWidth());
        btn_minimum->setSizePolicy(sizePolicy);
        btn_minimum->setMinimumSize(QSize(29, 21));
        btn_minimum->setMaximumSize(QSize(29, 21));
        btn_minimum->setCursor(QCursor(Qt::PointingHandCursor));

        horizontalLayout->addWidget(btn_minimum);

        btn_close = new QPushButton(widget_2);
        btn_close->setObjectName(QStringLiteral("btn_close"));
        sizePolicy.setHeightForWidth(btn_close->sizePolicy().hasHeightForWidth());
        btn_close->setSizePolicy(sizePolicy);
        btn_close->setMinimumSize(QSize(28, 21));
        btn_close->setMaximumSize(QSize(28, 21));
        btn_close->setCursor(QCursor(Qt::PointingHandCursor));

        horizontalLayout->addWidget(btn_close);

        horizontalSpacer_2 = new QSpacerItem(6, 20, QSizePolicy::Minimum, QSizePolicy::Minimum);

        horizontalLayout->addItem(horizontalSpacer_2);


        retranslateUi(AddLinkageRule);

        QMetaObject::connectSlotsByName(AddLinkageRule);
    } // setupUi

    void retranslateUi(QDialog *AddLinkageRule)
    {
        AddLinkageRule->setWindowTitle(QApplication::translate("AddLinkageRule", "Dialog", Q_NULLPTR));
        btnSelAlarmSource->setText(QApplication::translate("AddLinkageRule", ">", Q_NULLPTR));
        cbMap->setText(QApplication::translate("AddLinkageRule", "MAP", Q_NULLPTR));
        label_2->setText(QApplication::translate("AddLinkageRule", "ALARM TYPE", Q_NULLPTR));
        label->setText(QApplication::translate("AddLinkageRule", "RULE NAME", Q_NULLPTR));
        btnOK->setText(QApplication::translate("AddLinkageRule", "SAVE", Q_NULLPTR));
        label_5->setText(QApplication::translate("AddLinkageRule", "ACTION PARAM", Q_NULLPTR));
        cbRecord->setText(QApplication::translate("AddLinkageRule", "RECORD", Q_NULLPTR));
        cbPreview->setText(QApplication::translate("AddLinkageRule", "POP IMAGE", Q_NULLPTR));
        label_4->setText(QApplication::translate("AddLinkageRule", "LINKAGE ACTION", Q_NULLPTR));
        btnCancel->setText(QApplication::translate("AddLinkageRule", "CANCEL", Q_NULLPTR));
        label_3->setText(QApplication::translate("AddLinkageRule", "ALARM SOURCE", Q_NULLPTR));
        cbTVWall->setText(QApplication::translate("AddLinkageRule", "TVWALL", Q_NULLPTR));
        cbCapture->setText(QApplication::translate("AddLinkageRule", "CAPTURE", Q_NULLPTR));
        cbPTZ->setText(QApplication::translate("AddLinkageRule", "PTZ", Q_NULLPTR));
        label_6->setText(QApplication::translate("AddLinkageRule", "REMARKS", Q_NULLPTR));
        label_7->setText(QApplication::translate("AddLinkageRule", "Add Linkage Rule", Q_NULLPTR));
        btn_minimum->setText(QString());
        btn_close->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class AddLinkageRule: public Ui_AddLinkageRule {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ADDLINKAGERULE_H
